name: unifesta
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.2.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  

flutter:
  uses-material-design: true

  assets:
    - assets/images/event_illumination.png
    - assets/images/img1.jpg
    - assets/images/img2.jpg
    - assets/images/img3.jpg
    - assets/images/img4.jpg
    - assets/images/event 1.jpg
    - assets/images/event 2.jpg
    - assets/images/event 3.jpg
    - assets/images/event 4.jpg
    - assets/images/event 5.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"  
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"





